// KQL script
// Use management commands in this script to configure your database items, such as tables, functions, materialized views, and more.


.create-merge table ['weather-table-bq'] (name:string, region:string, country:string, lat:real, lon:real, localtime:string, temp_c:real, is_day:long, condition_text:string, condition_icon:string, wind_kph:real, wind_degree:long, wind_dir:string, pressure_in:real, precip_in:real, humidity:long, cloud:long, feelslike_c:real, uv:real, air_quality:dynamic, alerts:dynamic, forecast:dynamic, EventProcessedUtcTime:datetime, PartitionId:long, EventEnqueuedUtcTime:datetime) 
